blogs:
  - "docs/zh/docs/blogs/*"
  - "docs/zh/docs/en/blogs/*"

contact:
  - "docs/zh/docs/contact/*"
  - "docs/zh/docs/en/contact/*"

dak:
  - "docs/zh/docs/dak/**/*"
  - "docs/zh/docs/en/dak/**/*"

dev:
  - "scripts/**/*"
  - ".github/**/*"

models:
  - "docs/zh/docs/models/**/*"
  - "docs/zh/docs/en/models/**/*"

leopard:
  - "docs/zh/docs/leopard/**/*"
  - "docs/zh/docs/en/leopard/**/*"

open:
  - "docs/zh/docs/open/**/*"
  - "docs/zh/docs/en/open/**/*"

zestu:
  - "docs/zh/docs/zestu/**/*"
  - "docs/zh/docs/en/zestu/**/*"
