baize:
  - "docs/zh/docs/baize/**/*"

buy:
  - "docs/zh/docs/buy/**/*"

dak:
  - "docs/zh/docs/dak/**/*"

dmc:
  - "docs/zh/docs/dmc/**/*"

dtx:
  - "docs/zh/docs/dtx/**/*"

ghippo:
  - "docs/zh/docs/ghippo/**/*"

insight:
  - "docs/zh/docs/insight/**/*"

kpanda:
  - "docs/zh/docs/kpanda/**/*"

monkey:
  - "docs/zh/docs/monkey/**/*"

news:
  - "docs/zh/docs/news/**/*"

dev:
  - "scripts/**/*"
  - ".github/**/*"
